// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 RyzenStatus

import Foundation
import AppKit

/// Category or severity of an automated diagnostic insight.
enum InsightSeverity: String, Codable, Sendable, Comparable {
    case info
    case warning
    case critical

    static func < (lhs: InsightSeverity, rhs: InsightSeverity) -> Bool {
        switch (lhs, rhs) {
        case (.info, .warning), (.info, .critical), (.warning, .critical):
            return true
        default:
            return false
        }
    }
}

/// Diagnostic insight card model generated by InsightEngine.
struct InsightCard: Identifiable, Sendable, Codable, Equatable {
    var id: String
    var title: String
    var detail: String
    var severity: InsightSeverity
    var categoryName: String
    var actionHint: String?
    var timestamp: Date

    init(id: String = UUID().uuidString, title: String, detail: String, severity: InsightSeverity, categoryName: String, actionHint: String? = nil, timestamp: Date = Date()) {
        self.id = id
        self.title = title
        self.detail = detail
        self.severity = severity
        self.categoryName = categoryName
        self.actionHint = actionHint
        self.timestamp = timestamp
    }
}

/// Automated diagnostic engine synthesizing system performance insights.
final class InsightEngine: @unchecked Sendable {
    static let shared = InsightEngine()

    private init() {}

    /// Evaluates current system snapshot and process stats to produce active diagnostic insight cards.
    func evaluate(snapshot: SystemSnapshot, processes: [ProcessUsage]) -> [InsightCard] {
        var cards: [InsightCard] = []

        // 1. Memory Leak Detection Insights
        let leaks = ProcessUsageService.shared.leakingPIDs
        for pid in leaks {
            let procName = processes.first(where: { $0.pid == pid })?.name ?? "PID \(pid)"
            
            cards.append(InsightCard(
                id: "leak-\(pid)",
                title: "\(procName) Memory Leak Warning",
                detail: "Continuous memory growth detected over 20+ minutes with sustained slope and high confidence (R² ≥ 0.85).",
                severity: .critical,
                categoryName: "Memory",
                actionHint: "Inspect or force-quit process"
            ))
        }

        // 2. High CPU Runaway Process Insight
        if let topProc = processes.filter({ $0.value > 90.0 }).first {
            cards.append(InsightCard(
                id: "cpu-runaway-\(topProc.pid)",
                title: "\(topProc.name) High CPU Load",
                detail: "Consuming \(String(format: "%.1f%%", topProc.value)) CPU on the system.",
                severity: topProc.value > 200.0 ? .critical : .warning,
                categoryName: "CPU",
                actionHint: "Check if application is responsive"
            ))
        }

        // 3. High Memory Pressure Event Insight
        let pressure = snapshot.memoryPressure
        if pressure == .warning || pressure == .critical {
            cards.append(InsightCard(
                id: "mem-pressure-\(pressure)",
                title: pressure == .critical ? "Critical Memory Pressure" : "Elevated Memory Pressure",
                detail: "macOS is compressing memory pages or swapping to disk. Close unused applications to restore speed.",
                severity: pressure == .critical ? .critical : .warning,
                categoryName: "RAM",
                actionHint: "Purge or close heavy apps"
            ))
        }

        // 4. Rosetta 2 Translation Overhead Insight (Apple Silicon arm64 target only)
        #if arch(arm64)
        var rosettaProcesses: [String] = []
        for proc in processes {
            if proc.name.contains("(x86_64)") || proc.name.lowercased().contains("rosetta") {
                rosettaProcesses.append(proc.name)
            }
        }
        if !rosettaProcesses.isEmpty {
            cards.append(InsightCard(
                id: "rosetta-apps",
                title: "Rosetta 2 Translation Running",
                detail: "\(rosettaProcesses.count) x86_64 application(s) running via emulation (\(rosettaProcesses.prefix(3).joined(separator: ", "))).",
                severity: .info,
                categoryName: "Architecture",
                actionHint: "Upgrade to native Apple Silicon / Universal builds if available"
            ))
        }
        #endif

        // 5. High Temperature Insight
        if let cpuTemp = snapshot.cpuTemperature, cpuTemp > 85.0 {
            cards.append(InsightCard(
                id: "cpu-temp-high",
                title: "High CPU Temperature (\(String(format: "%.1f°C", cpuTemp)))",
                detail: "Thermal throttling may occur if temperatures remain above 90°C.",
                severity: cpuTemp > 92.0 ? .critical : .warning,
                categoryName: "Thermal",
                actionHint: "Ensure proper airflow or reduce heavy workload"
            ))
        }

        return cards.sorted { $0.severity > $1.severity }
    }
}
