// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 RyzenStatus

import Foundation

/// Strings for the Now Playing feature: its settings page and the menu panel
/// section. Same contract as the other FeatureStrings structs: memberwise
/// init with labeled arguments in declaration order, one static per language.
struct NowPlayingStrings {
    let pageTitle: String
    let hubDescription: String
    let menuBarModeLabel: String
    let menuBarModeIconOnly: String
    let menuBarModeArtist: String
    let menuBarModeSong: String
    let menuBarModeBoth: String
    let menuBarProgress: String
    let providerLabel: String
    let providerAuto: String
    let providerMusic: String
    let providerSpotify: String
    let openInAppToggle: String
    let openInAppCaption: String
    let artworkToggle: String
    let artworkAnimationToggle: String
    let artworkSizeLabel: String
    let marqueeToggle: String
    let marqueeSlideToggle: String
    let clearMediaCacheButton: String
    let unloadWhenHiddenToggle: String
    let emptyState: String
    let playLabel: String
    let pauseLabel: String
    let previousLabel: String
    let nextLabel: String
    let shuffleLabel: String
    let repeatLabel: String
    let repeatOffLabel: String
    let repeatAllLabel: String
    let repeatOneLabel: String
    let openInAppLabel: String
    let seekLabel: String
    let miniModeLabel: String
    let regularModeLabel: String
    let detachLabel: String
    let alwaysOnTopLabel: String
    let sizeLabel: String
    let sizeSmall: String
    let sizeMedium: String
    let sizeLarge: String
    let closeLabel: String
    // Details pane: lyrics, credits and the provider-aware search lane.
    let lyricsTab: String
    let creditsTab: String
    let lyricsLoading: String
    let lyricsUnavailable: String
    let lyricsFailed: String
    let retryLabel: String
    let creditsUnavailable: String
    let sourceFormat: String
    let searchMusicPlaceholder: String
    let searchSpotifyPlaceholder: String
    let searchPlayAction: String
    let searchOpenAction: String
    let creditsContributors: String
    let creditsRelease: String
    let creditsCatalog: String
    let creditsArtist: String
    let creditsAlbumArtist: String
    let creditsComposer: String
    let creditsAlbum: String
    let creditsGenre: String
    let creditsYear: String
    let creditsTrackNumber: String
}

extension FeatureStrings {
    static func nowPlaying(_ language: AppLanguage) -> NowPlayingStrings {
        switch language {
        case .enUS: return .enUS
        case .ptBR: return .ptBR
        case .tr: return .tr
        case .ru: return .ru
        case .es: return .es
        case .de: return .de
        case .fr: return .fr
        case .it: return .it
        case .ja: return .ja
        case .ko: return .ko
        case .zhHans: return .zhHans
        case .zhTW: return .zhTW
        case .zhHK: return .zhHK
        }
    }
}

extension NowPlayingStrings {
    static let enUS = NowPlayingStrings(
        pageTitle: "Now Playing",
        hubDescription: "Show the current track in the menu bar and the panel",
        menuBarModeLabel: "Menu bar text",
        menuBarModeIconOnly: "Icon only",
        menuBarModeArtist: "Artist",
        menuBarModeSong: "Song",
        menuBarModeBoth: "Artist + Song",
        menuBarProgress: "Progress bar in menu bar",
        providerLabel: "Preferred provider",
        providerAuto: "Auto",
        providerMusic: "Apple Music",
        providerSpotify: "Spotify",
        openInAppToggle: "Open source app on click",
        openInAppCaption: "Click the track title to jump to the app playing it",
        artworkToggle: "Show artwork",
        artworkAnimationToggle: "Animate artwork",
        artworkSizeLabel: "Artwork size",
        marqueeToggle: "Scroll long titles in the menu bar",
        marqueeSlideToggle: "Slide the text in on track change",
        clearMediaCacheButton: "Clear media cache",
        unloadWhenHiddenToggle: "Unload popup while hidden",
        emptyState: "Nothing playing",
        playLabel: "Play",
        pauseLabel: "Pause",
        previousLabel: "Previous track",
        nextLabel: "Next track",
        shuffleLabel: "Shuffle",
        repeatLabel: "Repeat",
        repeatOffLabel: "Repeat off",
        repeatAllLabel: "Repeat all",
        repeatOneLabel: "Repeat one",
        openInAppLabel: "Open in App",
        seekLabel: "Seek",
        miniModeLabel: "Mini mode",
        regularModeLabel: "Regular mode",
        detachLabel: "Detach to window",
        alwaysOnTopLabel: "Always on top",
        sizeLabel: "Size",
        sizeSmall: "Small",
        sizeMedium: "Medium",
        sizeLarge: "Large",
        closeLabel: "Close",
        lyricsTab: "Lyrics",
        creditsTab: "Credits",
        lyricsLoading: "Fetching lyrics…",
        lyricsUnavailable: "Lyrics unavailable for this track",
        lyricsFailed: "Lyrics couldn't be loaded",
        retryLabel: "Retry",
        creditsUnavailable: "Credits unavailable for this track",
        sourceFormat: "Source: %@",
        searchMusicPlaceholder: "Search Music library",
        searchSpotifyPlaceholder: "Search Spotify",
        searchPlayAction: "Play",
        searchOpenAction: "Open",
        creditsContributors: "Contributors",
        creditsRelease: "Release",
        creditsCatalog: "Catalog",
        creditsArtist: "Artist",
        creditsAlbumArtist: "Album Artist",
        creditsComposer: "Composer",
        creditsAlbum: "Album",
        creditsGenre: "Genre",
        creditsYear: "Year",
        creditsTrackNumber: "Track"
    )

    static let ptBR = NowPlayingStrings(
        pageTitle: "Em reprodução",
        hubDescription: "Mostra a faixa atual na barra de menus e no painel",
        menuBarModeLabel: "Texto da barra de menus",
        menuBarModeIconOnly: "Somente ícone",
        menuBarModeArtist: "Artista",
        menuBarModeSong: "Faixa",
        menuBarModeBoth: "Artista + Faixa",
        menuBarProgress: "Barra de progresso na barra de menus",
        providerLabel: "Provedor preferido",
        providerAuto: "Automático",
        providerMusic: "Apple Music",
        providerSpotify: "Spotify",
        openInAppToggle: "Abrir o app de origem ao clicar",
        openInAppCaption: "Clique no título da faixa para ir ao app que a reproduz",
        artworkToggle: "Mostrar capa",
        artworkAnimationToggle: "Animar capa",
        artworkSizeLabel: "Tamanho da capa",
        marqueeToggle: "Rolar títulos longos na barra de menus",
        marqueeSlideToggle: "Deslizar o texto ao trocar de faixa",
        clearMediaCacheButton: "Limpar cache de mídia",
        unloadWhenHiddenToggle: "Descarregar o popup enquanto oculto",
        emptyState: "Nada em reprodução",
        playLabel: "Reproduzir",
        pauseLabel: "Pausar",
        previousLabel: "Faixa anterior",
        nextLabel: "Próxima faixa",
        shuffleLabel: "Aleatório",
        repeatLabel: "Repetir",
        repeatOffLabel: "Repetição desativada",
        repeatAllLabel: "Repetir tudo",
        repeatOneLabel: "Repetir uma",
        openInAppLabel: "Abrir no app",
        seekLabel: "Buscar",
        miniModeLabel: "Modo mini",
        regularModeLabel: "Modo normal",
        detachLabel: "Destacar em janela",
        alwaysOnTopLabel: "Sempre no topo",
        sizeLabel: "Tamanho",
        sizeSmall: "Pequeno",
        sizeMedium: "Médio",
        sizeLarge: "Grande",
        closeLabel: "Fechar",
        lyricsTab: "Letras",
        creditsTab: "Créditos",
        lyricsLoading: "Buscando letra…",
        lyricsUnavailable: "Letra indisponível para esta faixa",
        lyricsFailed: "Não foi possível carregar a letra",
        retryLabel: "Tentar novamente",
        creditsUnavailable: "Créditos indisponíveis para esta faixa",
        sourceFormat: "Fonte: %@",
        searchMusicPlaceholder: "Buscar na biblioteca do Music",
        searchSpotifyPlaceholder: "Buscar no Spotify",
        searchPlayAction: "Reproduzir",
        searchOpenAction: "Abrir",
        creditsContributors: "Colaboradores",
        creditsRelease: "Lançamento",
        creditsCatalog: "Catálogo",
        creditsArtist: "Artista",
        creditsAlbumArtist: "Artista do álbum",
        creditsComposer: "Compositor",
        creditsAlbum: "Álbum",
        creditsGenre: "Gênero",
        creditsYear: "Ano",
        creditsTrackNumber: "Faixa"
    )

    static let tr = NowPlayingStrings(
        pageTitle: "Çalınan",
        hubDescription: "Çalan parçayı menü çubuğunda ve panelde göster",
        menuBarModeLabel: "Menü çubuğu metni",
        menuBarModeIconOnly: "Sadece simge",
        menuBarModeArtist: "Sanatçı",
        menuBarModeSong: "Parça",
        menuBarModeBoth: "Sanatçı + Parça",
        menuBarProgress: "Menü çubuğunda ilerleme çubuğu",
        providerLabel: "Tercih edilen sağlayıcı",
        providerAuto: "Otomatik",
        providerMusic: "Apple Music",
        providerSpotify: "Spotify",
        openInAppToggle: "Tıklayınca kaynak uygulamayı aç",
        openInAppCaption: "Parça başlığına tıklayarak onu çalan uygulamaya geç",
        artworkToggle: "Kapak resmini göster",
        artworkAnimationToggle: "Kapak animasyonu",
        artworkSizeLabel: "Kapak boyutu",
        marqueeToggle: "Uzun başlıkları menü çubuğunda kaydır",
        marqueeSlideToggle: "Parça değişince metni kaydırarak göster",
        clearMediaCacheButton: "Medya önbelleğini temizle",
        unloadWhenHiddenToggle: "Gizliyken pencere içeriğini boşalt",
        emptyState: "Çalan bir şey yok",
        playLabel: "Çal",
        pauseLabel: "Duraklat",
        previousLabel: "Önceki parça",
        nextLabel: "Sonraki parça",
        shuffleLabel: "Karıştır",
        repeatLabel: "Tekrarla",
        repeatOffLabel: "Tekrar kapalı",
        repeatAllLabel: "Tümünü tekrarla",
        repeatOneLabel: "Parçayı tekrarla",
        openInAppLabel: "Uygulamada aç",
        seekLabel: "İlerlet",
        miniModeLabel: "Mini mod",
        regularModeLabel: "Normal mod",
        detachLabel: "Pencereye ayır",
        alwaysOnTopLabel: "Her zaman üstte",
        sizeLabel: "Boyut",
        sizeSmall: "Küçük",
        sizeMedium: "Orta",
        sizeLarge: "Büyük",
        closeLabel: "Kapat",
        lyricsTab: "Şarkı sözleri",
        creditsTab: "Künye",
        lyricsLoading: "Şarkı sözleri alınıyor…",
        lyricsUnavailable: "Bu parça için şarkı sözleri yok",
        lyricsFailed: "Şarkı sözleri yüklenemedi",
        retryLabel: "Tekrar dene",
        creditsUnavailable: "Bu parça için künye yok",
        sourceFormat: "Kaynak: %@",
        searchMusicPlaceholder: "Music kitaplığında ara",
        searchSpotifyPlaceholder: "Spotify'da ara",
        searchPlayAction: "Çal",
        searchOpenAction: "Aç",
        creditsContributors: "Katkıda bulunanlar",
        creditsRelease: "Yayın",
        creditsCatalog: "Katalog",
        creditsArtist: "Sanatçı",
        creditsAlbumArtist: "Albüm Sanatçısı",
        creditsComposer: "Besteci",
        creditsAlbum: "Albüm",
        creditsGenre: "Tür",
        creditsYear: "Yıl",
        creditsTrackNumber: "Parça"
    )

    static let ru = NowPlayingStrings(
        pageTitle: "Сейчас играет",
        hubDescription: "Показывает текущий трек в строке меню и панели",
        menuBarModeLabel: "Текст в строке меню",
        menuBarModeIconOnly: "Только значок",
        menuBarModeArtist: "Исполнитель",
        menuBarModeSong: "Трек",
        menuBarModeBoth: "Исполнитель + трек",
        menuBarProgress: "Полоса прогресса в строке меню",
        providerLabel: "Предпочитаемый источник",
        providerAuto: "Авто",
        providerMusic: "Apple Music",
        providerSpotify: "Spotify",
        openInAppToggle: "Открывать исходное приложение по клику",
        openInAppCaption: "Нажмите на название трека, чтобы перейти к приложению, в котором он играет",
        artworkToggle: "Показывать обложку",
        artworkAnimationToggle: "Анимация обложки",
        artworkSizeLabel: "Размер обложки",
        marqueeToggle: "Прокручивать длинные названия в строке меню",
        marqueeSlideToggle: "Скольжение текста при смене трека",
        clearMediaCacheButton: "Очистить кеш медиа",
        unloadWhenHiddenToggle: "Выгружать попап, пока скрыт",
        emptyState: "Ничего не играет",
        playLabel: "Играть",
        pauseLabel: "Пауза",
        previousLabel: "Предыдущий трек",
        nextLabel: "Следующий трек",
        shuffleLabel: "Перемешать",
        repeatLabel: "Повтор",
        repeatOffLabel: "Повтор выключен",
        repeatAllLabel: "Повтор всех",
        repeatOneLabel: "Повтор одной",
        openInAppLabel: "Открыть в приложении",
        seekLabel: "Перемотка",
        miniModeLabel: "Мини-режим",
        regularModeLabel: "Обычный режим",
        detachLabel: "Открепить в окно",
        alwaysOnTopLabel: "Поверх всех окон",
        sizeLabel: "Размер",
        sizeSmall: "Маленький",
        sizeMedium: "Средний",
        sizeLarge: "Большой",
        closeLabel: "Закрыть",
        lyricsTab: "Текст песни",
        creditsTab: "Авторы",
        lyricsLoading: "Загрузка текста…",
        lyricsUnavailable: "Текст этого трека недоступен",
        lyricsFailed: "Не удалось загрузить текст",
        retryLabel: "Повторить",
        creditsUnavailable: "Авторы этого трека недоступны",
        sourceFormat: "Источник: %@",
        searchMusicPlaceholder: "Поиск в медиатеке Music",
        searchSpotifyPlaceholder: "Поиск в Spotify",
        searchPlayAction: "Играть",
        searchOpenAction: "Открыть",
        creditsContributors: "Участники",
        creditsRelease: "Релиз",
        creditsCatalog: "Каталог",
        creditsArtist: "Исполнитель",
        creditsAlbumArtist: "Исполнитель альбома",
        creditsComposer: "Композитор",
        creditsAlbum: "Альбом",
        creditsGenre: "Жанр",
        creditsYear: "Год",
        creditsTrackNumber: "Трек"
    )

    static let es = NowPlayingStrings(
        pageTitle: "En reproducción",
        hubDescription: "Muestra la canción actual en la barra de menús y el panel",
        menuBarModeLabel: "Texto de la barra de menús",
        menuBarModeIconOnly: "Solo icono",
        menuBarModeArtist: "Artista",
        menuBarModeSong: "Canción",
        menuBarModeBoth: "Artista + Canción",
        menuBarProgress: "Barra de progreso en la barra de menús",
        providerLabel: "Proveedor preferido",
        providerAuto: "Automático",
        providerMusic: "Apple Music",
        providerSpotify: "Spotify",
        openInAppToggle: "Abrir la app de origen al hacer clic",
        openInAppCaption: "Haz clic en el título de la canción para ir a la app que la reproduce",
        artworkToggle: "Mostrar carátula",
        artworkAnimationToggle: "Animar carátula",
        artworkSizeLabel: "Tamaño de la carátula",
        marqueeToggle: "Desplazar títulos largos en la barra de menús",
        marqueeSlideToggle: "Deslizar el texto al cambiar de canción",
        clearMediaCacheButton: "Borrar caché multimedia",
        unloadWhenHiddenToggle: "Descargar el popup mientras está oculto",
        emptyState: "No hay nada en reproducción",
        playLabel: "Reproducir",
        pauseLabel: "Pausa",
        previousLabel: "Canción anterior",
        nextLabel: "Canción siguiente",
        shuffleLabel: "Aleatorio",
        repeatLabel: "Repetir",
        repeatOffLabel: "Repetición desactivada",
        repeatAllLabel: "Repetir todo",
        repeatOneLabel: "Repetir una",
        openInAppLabel: "Abrir en la app",
        seekLabel: "Buscar",
        miniModeLabel: "Modo mini",
        regularModeLabel: "Modo normal",
        detachLabel: "Separar en ventana",
        alwaysOnTopLabel: "Siempre encima",
        sizeLabel: "Tamaño",
        sizeSmall: "Pequeño",
        sizeMedium: "Mediano",
        sizeLarge: "Grande",
        closeLabel: "Cerrar",
        lyricsTab: "Letra",
        creditsTab: "Créditos",
        lyricsLoading: "Buscando la letra…",
        lyricsUnavailable: "Letra no disponible para esta canción",
        lyricsFailed: "No se pudo cargar la letra",
        retryLabel: "Reintentar",
        creditsUnavailable: "Créditos no disponibles para esta canción",
        sourceFormat: "Fuente: %@",
        searchMusicPlaceholder: "Buscar en la biblioteca de Music",
        searchSpotifyPlaceholder: "Buscar en Spotify",
        searchPlayAction: "Reproducir",
        searchOpenAction: "Abrir",
        creditsContributors: "Colaboradores",
        creditsRelease: "Lanzamiento",
        creditsCatalog: "Catálogo",
        creditsArtist: "Artista",
        creditsAlbumArtist: "Artista del álbum",
        creditsComposer: "Compositor",
        creditsAlbum: "Álbum",
        creditsGenre: "Género",
        creditsYear: "Año",
        creditsTrackNumber: "Pista"
    )

    static let de = NowPlayingStrings(
        pageTitle: "Aktueller Titel",
        hubDescription: "Zeigt den aktuellen Titel in der Menüleiste und im Panel an",
        menuBarModeLabel: "Menüleistentext",
        menuBarModeIconOnly: "Nur Symbol",
        menuBarModeArtist: "Künstler",
        menuBarModeSong: "Titel",
        menuBarModeBoth: "Künstler + Titel",
        menuBarProgress: "Fortschrittsbalken in der Menüleiste",
        providerLabel: "Bevorzugter Anbieter",
        providerAuto: "Automatisch",
        providerMusic: "Apple Music",
        providerSpotify: "Spotify",
        openInAppToggle: "Quell-App bei Klick öffnen",
        openInAppCaption: "Klicke auf den Titel, um zur App zu springen, die ihn abspielt",
        artworkToggle: "Cover anzeigen",
        artworkAnimationToggle: "Cover animieren",
        artworkSizeLabel: "Covergröße",
        marqueeToggle: "Lange Titel in der Menüleiste scrollen",
        marqueeSlideToggle: "Text beim Titelwechsel gleiten lassen",
        clearMediaCacheButton: "Medien-Cache leeren",
        unloadWhenHiddenToggle: "Popup im verborgenen Zustand entladen",
        emptyState: "Nichts wird abgespielt",
        playLabel: "Abspielen",
        pauseLabel: "Pause",
        previousLabel: "Vorheriger Titel",
        nextLabel: "Nächster Titel",
        shuffleLabel: "Zufallswiedergabe",
        repeatLabel: "Wiederholen",
        repeatOffLabel: "Wiederholen aus",
        repeatAllLabel: "Alle wiederholen",
        repeatOneLabel: "Titel wiederholen",
        openInAppLabel: "In App öffnen",
        seekLabel: "Springen",
        miniModeLabel: "Mini-Modus",
        regularModeLabel: "Normaler Modus",
        detachLabel: "In Fenster lösen",
        alwaysOnTopLabel: "Immer im Vordergrund",
        sizeLabel: "Größe",
        sizeSmall: "Klein",
        sizeMedium: "Mittel",
        sizeLarge: "Groß",
        closeLabel: "Schließen",
        lyricsTab: "Liedtext",
        creditsTab: "Mitwirkende",
        lyricsLoading: "Liedtext wird geladen…",
        lyricsUnavailable: "Für diesen Titel ist kein Liedtext verfügbar",
        lyricsFailed: "Liedtext konnte nicht geladen werden",
        retryLabel: "Erneut versuchen",
        creditsUnavailable: "Für diesen Titel sind keine Mitwirkenden verfügbar",
        sourceFormat: "Quelle: %@",
        searchMusicPlaceholder: "Music-Mediathek durchsuchen",
        searchSpotifyPlaceholder: "Spotify durchsuchen",
        searchPlayAction: "Abspielen",
        searchOpenAction: "Öffnen",
        creditsContributors: "Beteiligte",
        creditsRelease: "Veröffentlichung",
        creditsCatalog: "Katalog",
        creditsArtist: "Künstler",
        creditsAlbumArtist: "Albumkünstler",
        creditsComposer: "Komponist",
        creditsAlbum: "Album",
        creditsGenre: "Genre",
        creditsYear: "Jahr",
        creditsTrackNumber: "Titel"
    )

    static let fr = NowPlayingStrings(
        pageTitle: "En cours de lecture",
        hubDescription: "Affiche le morceau en cours dans la barre des menus et le panneau",
        menuBarModeLabel: "Texte de la barre des menus",
        menuBarModeIconOnly: "Icône uniquement",
        menuBarModeArtist: "Artiste",
        menuBarModeSong: "Morceau",
        menuBarModeBoth: "Artiste + Morceau",
        menuBarProgress: "Barre de progression dans la barre des menus",
        providerLabel: "Fournisseur préféré",
        providerAuto: "Automatique",
        providerMusic: "Apple Music",
        providerSpotify: "Spotify",
        openInAppToggle: "Ouvrir l'app source au clic",
        openInAppCaption: "Cliquez sur le titre du morceau pour accéder à l'app qui le diffuse",
        artworkToggle: "Afficher la pochette",
        artworkAnimationToggle: "Animer la pochette",
        artworkSizeLabel: "Taille de la pochette",
        marqueeToggle: "Faire défiler les longs titres dans la barre des menus",
        marqueeSlideToggle: "Faire glisser le texte au changement de morceau",
        clearMediaCacheButton: "Vider le cache multimédia",
        unloadWhenHiddenToggle: "Décharger la fenêtre quand elle est masquée",
        emptyState: "Rien en cours de lecture",
        playLabel: "Lire",
        pauseLabel: "Pause",
        previousLabel: "Morceau précédent",
        nextLabel: "Morceau suivant",
        shuffleLabel: "Aléatoire",
        repeatLabel: "Répéter",
        repeatOffLabel: "Répétition désactivée",
        repeatAllLabel: "Tout répéter",
        repeatOneLabel: "Répéter un morceau",
        openInAppLabel: "Ouvrir dans l'app",
        seekLabel: "Rechercher",
        miniModeLabel: "Mode mini",
        regularModeLabel: "Mode normal",
        detachLabel: "Détacher dans une fenêtre",
        alwaysOnTopLabel: "Toujours au premier plan",
        sizeLabel: "Taille",
        sizeSmall: "Petit",
        sizeMedium: "Moyen",
        sizeLarge: "Grand",
        closeLabel: "Fermer",
        lyricsTab: "Paroles",
        creditsTab: "Crédits",
        lyricsLoading: "Récupération des paroles…",
        lyricsUnavailable: "Paroles indisponibles pour ce morceau",
        lyricsFailed: "Impossible de charger les paroles",
        retryLabel: "Réessayer",
        creditsUnavailable: "Crédits indisponibles pour ce morceau",
        sourceFormat: "Source : %@",
        searchMusicPlaceholder: "Rechercher dans Music",
        searchSpotifyPlaceholder: "Rechercher sur Spotify",
        searchPlayAction: "Lire",
        searchOpenAction: "Ouvrir",
        creditsContributors: "Contributeurs",
        creditsRelease: "Sortie",
        creditsCatalog: "Catalogue",
        creditsArtist: "Artiste",
        creditsAlbumArtist: "Artiste de l'album",
        creditsComposer: "Compositeur",
        creditsAlbum: "Album",
        creditsGenre: "Genre",
        creditsYear: "Année",
        creditsTrackNumber: "Piste"
    )

    static let it = NowPlayingStrings(
        pageTitle: "In riproduzione",
        hubDescription: "Mostra il brano in corso nella barra dei menu e nel pannello",
        menuBarModeLabel: "Testo della barra dei menu",
        menuBarModeIconOnly: "Solo icona",
        menuBarModeArtist: "Artista",
        menuBarModeSong: "Brano",
        menuBarModeBoth: "Artista + Brano",
        menuBarProgress: "Barra di avanzamento nella barra dei menu",
        providerLabel: "Provider preferito",
        providerAuto: "Automatico",
        providerMusic: "Apple Music",
        providerSpotify: "Spotify",
        openInAppToggle: "Apri l'app di origine al clic",
        openInAppCaption: "Fai clic sul titolo del brano per passare all'app che lo riproduce",
        artworkToggle: "Mostra copertina",
        artworkAnimationToggle: "Anima copertina",
        artworkSizeLabel: "Dimensione copertina",
        marqueeToggle: "Scorri i titoli lunghi nella barra dei menu",
        marqueeSlideToggle: "Fai scorrere il testo al cambio di brano",
        clearMediaCacheButton: "Svuota cache multimediale",
        unloadWhenHiddenToggle: "Scarica il popup quando è nascosto",
        emptyState: "Niente in riproduzione",
        playLabel: "Riproduci",
        pauseLabel: "Pausa",
        previousLabel: "Brano precedente",
        nextLabel: "Brano successivo",
        shuffleLabel: "Riproduzione casuale",
        repeatLabel: "Ripeti",
        repeatOffLabel: "Ripetizione disattivata",
        repeatAllLabel: "Ripeti tutto",
        repeatOneLabel: "Ripeti brano",
        openInAppLabel: "Apri nell'app",
        seekLabel: "Cerca",
        miniModeLabel: "Modalità mini",
        regularModeLabel: "Modalità normale",
        detachLabel: "Separa in finestra",
        alwaysOnTopLabel: "Sempre in primo piano",
        sizeLabel: "Dimensione",
        sizeSmall: "Piccolo",
        sizeMedium: "Medio",
        sizeLarge: "Grande",
        closeLabel: "Chiudi",
        lyricsTab: "Testo",
        creditsTab: "Crediti",
        lyricsLoading: "Recupero del testo…",
        lyricsUnavailable: "Testo non disponibile per questo brano",
        lyricsFailed: "Impossibile caricare il testo",
        retryLabel: "Riprova",
        creditsUnavailable: "Crediti non disponibili per questo brano",
        sourceFormat: "Fonte: %@",
        searchMusicPlaceholder: "Cerca nella libreria di Music",
        searchSpotifyPlaceholder: "Cerca su Spotify",
        searchPlayAction: "Riproduci",
        searchOpenAction: "Apri",
        creditsContributors: "Collaboratori",
        creditsRelease: "Pubblicazione",
        creditsCatalog: "Catalogo",
        creditsArtist: "Artista",
        creditsAlbumArtist: "Artista album",
        creditsComposer: "Compositore",
        creditsAlbum: "Album",
        creditsGenre: "Genere",
        creditsYear: "Anno",
        creditsTrackNumber: "Traccia"
    )

    static let ja = NowPlayingStrings(
        pageTitle: "再生中",
        hubDescription: "現在の曲をメニューバーとパネルに表示",
        menuBarModeLabel: "メニューバーのテキスト",
        menuBarModeIconOnly: "アイコンのみ",
        menuBarModeArtist: "アーティスト",
        menuBarModeSong: "曲名",
        menuBarModeBoth: "アーティスト + 曲名",
        menuBarProgress: "メニューバーにプログレスバー",
        providerLabel: "優先プロバイダ",
        providerAuto: "自動",
        providerMusic: "Apple Music",
        providerSpotify: "Spotify",
        openInAppToggle: "クリックで再生元アプリを開く",
        openInAppCaption: "曲名をクリックすると再生中のアプリに移動します",
        artworkToggle: "アートワークを表示",
        artworkAnimationToggle: "アートワークをアニメーション化",
        artworkSizeLabel: "アートワークのサイズ",
        marqueeToggle: "長いタイトルをメニューバーでスクロール",
        marqueeSlideToggle: "曲の切り替わりにテキストをスライド表示",
        clearMediaCacheButton: "メディアキャッシュを消去",
        unloadWhenHiddenToggle: "非表示中はポップアップを解放",
        emptyState: "再生中の曲はありません",
        playLabel: "再生",
        pauseLabel: "一時停止",
        previousLabel: "前の曲",
        nextLabel: "次の曲",
        shuffleLabel: "シャッフル",
        repeatLabel: "リピート",
        repeatOffLabel: "リピートオフ",
        repeatAllLabel: "すべてリピート",
        repeatOneLabel: "1曲リピート",
        openInAppLabel: "アプリで開く",
        seekLabel: "シーク",
        miniModeLabel: "ミニモード",
        regularModeLabel: "通常モード",
        detachLabel: "ウィンドウとして切り離す",
        alwaysOnTopLabel: "常に手前に表示",
        sizeLabel: "サイズ",
        sizeSmall: "小",
        sizeMedium: "中",
        sizeLarge: "大",
        closeLabel: "閉じる",
        lyricsTab: "歌詞",
        creditsTab: "クレジット",
        lyricsLoading: "歌詞を取得中…",
        lyricsUnavailable: "この曲の歌詞はありません",
        lyricsFailed: "歌詞を読み込めませんでした",
        retryLabel: "再試行",
        creditsUnavailable: "この曲のクレジットはありません",
        sourceFormat: "ソース: %@",
        searchMusicPlaceholder: "ミュージックライブラリを検索",
        searchSpotifyPlaceholder: "Spotifyで検索",
        searchPlayAction: "再生",
        searchOpenAction: "開く",
        creditsContributors: "参加者",
        creditsRelease: "リリース",
        creditsCatalog: "カタログ",
        creditsArtist: "アーティスト",
        creditsAlbumArtist: "アルバムアーティスト",
        creditsComposer: "作曲家",
        creditsAlbum: "アルバム",
        creditsGenre: "ジャンル",
        creditsYear: "年",
        creditsTrackNumber: "トラック"
    )

    static let ko = NowPlayingStrings(
        pageTitle: "재생 중",
        hubDescription: "현재 재생 중인 곡을 메뉴 막대와 패널에 표시",
        menuBarModeLabel: "메뉴 막대 텍스트",
        menuBarModeIconOnly: "아이콘만",
        menuBarModeArtist: "아티스트",
        menuBarModeSong: "곡",
        menuBarModeBoth: "아티스트 + 곡",
        menuBarProgress: "메뉴 막대에 진행 막대",
        providerLabel: "선호 공급자",
        providerAuto: "자동",
        providerMusic: "Apple Music",
        providerSpotify: "Spotify",
        openInAppToggle: "클릭하면 원본 앱 열기",
        openInAppCaption: "곡 제목을 클릭하면 재생 중인 앱으로 이동합니다",
        artworkToggle: "아트워크 표시",
        artworkAnimationToggle: "아트워크 애니메이션",
        artworkSizeLabel: "아트워크 크기",
        marqueeToggle: "메뉴 막대에서 긴 제목 스크롤",
        marqueeSlideToggle: "곡 변경 시 텍스트 슬라이드",
        clearMediaCacheButton: "미디어 캐시 지우기",
        unloadWhenHiddenToggle: "숨겨진 동안 팝업 메모리 해제",
        emptyState: "재생 중인 곡 없음",
        playLabel: "재생",
        pauseLabel: "일시 정지",
        previousLabel: "이전 곡",
        nextLabel: "다음 곡",
        shuffleLabel: "셔플",
        repeatLabel: "반복",
        repeatOffLabel: "반복 끄기",
        repeatAllLabel: "모두 반복",
        repeatOneLabel: "한 곡 반복",
        openInAppLabel: "앱에서 열기",
        seekLabel: "탐색",
        miniModeLabel: "미니 모드",
        regularModeLabel: "일반 모드",
        detachLabel: "창으로 분리",
        alwaysOnTopLabel: "항상 위에",
        sizeLabel: "크기",
        sizeSmall: "작게",
        sizeMedium: "보통",
        sizeLarge: "크게",
        closeLabel: "닫기",
        lyricsTab: "가사",
        creditsTab: "크레딧",
        lyricsLoading: "가사 가져오는 중…",
        lyricsUnavailable: "이 곡의 가사를 사용할 수 없습니다",
        lyricsFailed: "가사를 불러올 수 없습니다",
        retryLabel: "다시 시도",
        creditsUnavailable: "이 곡의 크레딧을 사용할 수 없습니다",
        sourceFormat: "출처: %@",
        searchMusicPlaceholder: "Music 보관함 검색",
        searchSpotifyPlaceholder: "Spotify 검색",
        searchPlayAction: "재생",
        searchOpenAction: "열기",
        creditsContributors: "참여자",
        creditsRelease: "발매",
        creditsCatalog: "카탈로그",
        creditsArtist: "아티스트",
        creditsAlbumArtist: "앨범 아티스트",
        creditsComposer: "작곡가",
        creditsAlbum: "앨범",
        creditsGenre: "장르",
        creditsYear: "연도",
        creditsTrackNumber: "트랙"
    )

    static let zhHans = NowPlayingStrings(
        pageTitle: "正在播放",
        hubDescription: "在菜单栏和面板中显示当前曲目",
        menuBarModeLabel: "菜单栏文本",
        menuBarModeIconOnly: "仅图标",
        menuBarModeArtist: "艺术家",
        menuBarModeSong: "歌曲",
        menuBarModeBoth: "艺术家 + 歌曲",
        menuBarProgress: "菜单栏中的进度条",
        providerLabel: "首选来源",
        providerAuto: "自动",
        providerMusic: "Apple Music",
        providerSpotify: "Spotify",
        openInAppToggle: "点击时打开来源应用",
        openInAppCaption: "点击歌曲标题可跳转到正在播放它的应用",
        artworkToggle: "显示封面",
        artworkAnimationToggle: "封面过渡动画",
        artworkSizeLabel: "封面大小",
        marqueeToggle: "在菜单栏滚动长标题",
        marqueeSlideToggle: "换曲时滑入文本",
        clearMediaCacheButton: "清除媒体缓存",
        unloadWhenHiddenToggle: "隐藏时卸载弹窗内容",
        emptyState: "没有正在播放的内容",
        playLabel: "播放",
        pauseLabel: "暂停",
        previousLabel: "上一首",
        nextLabel: "下一首",
        shuffleLabel: "随机播放",
        repeatLabel: "循环播放",
        repeatOffLabel: "关闭循环播放",
        repeatAllLabel: "循环播放全部",
        repeatOneLabel: "单曲循环",
        openInAppLabel: "在应用中打开",
        seekLabel: "跳转",
        miniModeLabel: "迷你模式",
        regularModeLabel: "常规模式",
        detachLabel: "分离为窗口",
        alwaysOnTopLabel: "始终置顶",
        sizeLabel: "大小",
        sizeSmall: "小",
        sizeMedium: "中",
        sizeLarge: "大",
        closeLabel: "关闭",
        lyricsTab: "歌词",
        creditsTab: "制作名单",
        lyricsLoading: "正在获取歌词…",
        lyricsUnavailable: "此歌曲没有歌词",
        lyricsFailed: "无法加载歌词",
        retryLabel: "重试",
        creditsUnavailable: "此歌曲没有制作信息",
        sourceFormat: "来源：%@",
        searchMusicPlaceholder: "搜索 Music 资料库",
        searchSpotifyPlaceholder: "搜索 Spotify",
        searchPlayAction: "播放",
        searchOpenAction: "打开",
        creditsContributors: "创作者",
        creditsRelease: "发行",
        creditsCatalog: "目录",
        creditsArtist: "艺术家",
        creditsAlbumArtist: "专辑艺术家",
        creditsComposer: "作曲",
        creditsAlbum: "专辑",
        creditsGenre: "流派",
        creditsYear: "年份",
        creditsTrackNumber: "曲目"
    )

    static let zhTW = NowPlayingStrings(
        pageTitle: "正在播放",
        hubDescription: "在選單列和面板中顯示目前曲目",
        menuBarModeLabel: "選單列文字",
        menuBarModeIconOnly: "僅圖示",
        menuBarModeArtist: "藝人",
        menuBarModeSong: "歌曲",
        menuBarModeBoth: "藝人 + 歌曲",
        menuBarProgress: "選單列中的進度列",
        providerLabel: "偏好的來源",
        providerAuto: "自動",
        providerMusic: "Apple Music",
        providerSpotify: "Spotify",
        openInAppToggle: "點按時開啟來源 App",
        openInAppCaption: "點按歌曲標題即可跳至播放它的 App",
        artworkToggle: "顯示封面",
        artworkAnimationToggle: "封面過場動畫",
        artworkSizeLabel: "封面大小",
        marqueeToggle: "在選單列捲動長標題",
        marqueeSlideToggle: "換曲時滑入文字",
        clearMediaCacheButton: "清除媒體快取",
        unloadWhenHiddenToggle: "隱藏時卸載彈出內容",
        emptyState: "沒有正在播放的內容",
        playLabel: "播放",
        pauseLabel: "暫停",
        previousLabel: "上一首",
        nextLabel: "下一首",
        shuffleLabel: "隨機播放",
        repeatLabel: "重複播放",
        repeatOffLabel: "關閉重複播放",
        repeatAllLabel: "重複播放全部",
        repeatOneLabel: "單曲重複",
        openInAppLabel: "在 App 中開啟",
        seekLabel: "跳轉",
        miniModeLabel: "迷你模式",
        regularModeLabel: "一般模式",
        detachLabel: "分離為視窗",
        alwaysOnTopLabel: "永遠置頂",
        sizeLabel: "大小",
        sizeSmall: "小",
        sizeMedium: "中",
        sizeLarge: "大",
        closeLabel: "關閉",
        lyricsTab: "歌詞",
        creditsTab: "製作名單",
        lyricsLoading: "正在取得歌詞…",
        lyricsUnavailable: "此歌曲沒有歌詞",
        lyricsFailed: "無法載入歌詞",
        retryLabel: "重試",
        creditsUnavailable: "此歌曲沒有製作資訊",
        sourceFormat: "來源：%@",
        searchMusicPlaceholder: "搜尋 Music 資料庫",
        searchSpotifyPlaceholder: "搜尋 Spotify",
        searchPlayAction: "播放",
        searchOpenAction: "開啟",
        creditsContributors: "創作者",
        creditsRelease: "發行",
        creditsCatalog: "目錄",
        creditsArtist: "藝人",
        creditsAlbumArtist: "專輯藝人",
        creditsComposer: "作曲",
        creditsAlbum: "專輯",
        creditsGenre: "類型",
        creditsYear: "年份",
        creditsTrackNumber: "曲目"
    )

    static let zhHK = NowPlayingStrings(
        pageTitle: "正在播放",
        hubDescription: "喺選單列同面板度顯示目前曲目",
        menuBarModeLabel: "選單列文字",
        menuBarModeIconOnly: "淨係圖示",
        menuBarModeArtist: "藝人",
        menuBarModeSong: "歌曲",
        menuBarModeBoth: "藝人 + 歌曲",
        menuBarProgress: "選單列入面嘅進度列",
        providerLabel: "偏好來源",
        providerAuto: "自動",
        providerMusic: "Apple Music",
        providerSpotify: "Spotify",
        openInAppToggle: "㩒嘅時候開啟來源 App",
        openInAppCaption: "㩒歌曲標題就可以跳去播放緊嘅 App",
        artworkToggle: "顯示封面",
        artworkAnimationToggle: "封面過場動畫",
        artworkSizeLabel: "封面大細",
        marqueeToggle: "喺選單列捲動長標題",
        marqueeSlideToggle: "換曲時滑入文字",
        clearMediaCacheButton: "清除媒體快取",
        unloadWhenHiddenToggle: "隱藏嗰陣卸載彈出內容",
        emptyState: "而家冇嘢播",
        playLabel: "播放",
        pauseLabel: "暫停",
        previousLabel: "上一首",
        nextLabel: "下一首",
        shuffleLabel: "隨機播放",
        repeatLabel: "重複播放",
        repeatOffLabel: "關閉重複播放",
        repeatAllLabel: "重複播放全部",
        repeatOneLabel: "單曲重複",
        openInAppLabel: "喺 App 度開啟",
        seekLabel: "跳轉",
        miniModeLabel: "迷你模式",
        regularModeLabel: "一般模式",
        detachLabel: "分離做視窗",
        alwaysOnTopLabel: "永遠置頂",
        sizeLabel: "大細",
        sizeSmall: "細",
        sizeMedium: "中",
        sizeLarge: "大",
        closeLabel: "關閉",
        lyricsTab: "歌詞",
        creditsTab: "製作名單",
        lyricsLoading: "攞緊歌詞…",
        lyricsUnavailable: "呢首歌冇歌詞",
        lyricsFailed: "載入唔到歌詞",
        retryLabel: "再試",
        creditsUnavailable: "呢首歌冇製作資訊",
        sourceFormat: "來源：%@",
        searchMusicPlaceholder: "搜尋 Music 媒體庫",
        searchSpotifyPlaceholder: "搜尋 Spotify",
        searchPlayAction: "播放",
        searchOpenAction: "開啟",
        creditsContributors: "創作者",
        creditsRelease: "發行",
        creditsCatalog: "目錄",
        creditsArtist: "藝人",
        creditsAlbumArtist: "專輯藝人",
        creditsComposer: "作曲",
        creditsAlbum: "專輯",
        creditsGenre: "類型",
        creditsYear: "年份",
        creditsTrackNumber: "曲目"
    )
}
